### ISSUE TITLE
Docker image not Working on Synology

### ISSUE THREAD

**Issue by Oktroun** [ich777/docker-vintage-story#1]
Last file is there an extracted but Docker image is not finding the data so server is not starting correctly.
Maybe something is wrong with config for docker in synology?
Hope you can help, thanks a lot.

![image](https://user-images.githubusercontent.com/19288410/113518423-8be30780-9586-11eb-9e52-b7914d048acf.png)
![image](https://user-images.githubusercontent.com/19288410/113518428-99988d00-9586-11eb-8590-95633ecc34e7.png)
![image](https://user-images.githubusercontent.com/19288410/113518435-a4ebb880-9586-11eb-8119-d0895d3fb4f6.png)

---Version Check---
---Vintage Story not found, downloading...---
---Can't download Vintage Story v1.14.8, putting server into sleep mode!---
![image](https://user-images.githubusercontent.com/19288410/113518379-47576c00-9586-11eb-86fa-3dadb339d272.png)

**Comment by ich777** [comment]
Are you sure that the UID & GID (99 & 100) exist on your Synology?

Please try to delete the vintagestory-1.14.8.tar.gz and also the vs_server_latest.tar, something seems weird with the folder structure, tested it now and the server runs fine on Unraid:
![grafik](https://user-images.githubusercontent.com/28066518/113540462-80242f00-95e0-11eb-903e-e961dfeeef22.png)


Here is also the output from the log after installing the Docker:
![grafik](https://user-images.githubusercontent.com/28066518/113540565-b2ce2780-95e0-11eb-883a-135b106acc1f.png)

**Comment by Oktroun** [comment]
Now I'm getting a little further. I changed the UID to 1035 this is the vintagestory user on my synology system.
He has the rights on the folder and is also the owner.
But know I get the following one:

![image](https://user-images.githubusercontent.com/19288410/113595268-1421e500-9639-11eb-9f2d-ca6f41f2aade.png)

**Comment by ich777** [comment]
@Oktroun Can you try to stop the container then, delete the container and pull it again from Docker Hub and also delete the contents of the entire folder that was created for Vintage Story in the first place?
I think you now got a permission problem...

EDIT: is the user with the UID 1035 a root user?

**Comment by Oktroun** [comment]
I will try.

@Edit: user is not a root user.

**Comment by Oktroun** [comment]
So now it works fine, I delete all and reinstall, so now it is perfect.
Do you have a donaten link?

Thanks for support.

**Comment by ich777** [comment]
@Oktroun glad to hear that it is now working... :)

If you need other game servers look in my steamcmd repo and open the branches. ;)

Sure thing: [Click](https://paypal.me/chips777)

**Comment by ich777** [comment]
I close this for now since everything is working now.
